### PR TITLE
begin() function is added to receive Begin callbcak instead of taking…

### PR DESCRIPTION
**Pull request by abdullahmahboob**
… the Begin callback in init() function. A bug is also removed.

### CODE REVIEW

**Comment by abdullahmahboob** [comment]
I like your idea! Let me think about the prettifying part.

**Comment by abdullahmahboob** [comment]
So, here's the new approach:
I renamed `Begin` to `Valve`. And I'm thinking of renaming `update` to `run`. `run` would have two overloaders. One with void and the other receiving `Valve` as callback.
Valve is open by default, so if the user does not pass any Valve callback, the SDK begins running right from the start. If the Valve callback is passed, the SDK only runs when it returns true.

**Comment by moizhusnain** [comment]
Great idea. Just one question! Why a callback? If it can be handled in relatively simpler way like passing a boolean.

**Comment by abdullahmahboob** [comment]
I did that to make it programmable. But on second thought, I think you may
be right. umm a Boolean could do it. Let me think about it. I'll get back
to you with the commit now IA.

**Comment by moizhusnain** [comment]
I loved the new examples. They are so great.

**Comment by abdullahmahboob** [comment]
They took most of my time. I was excited because of the feedbacks lol. 😂

**Pull request merged**
